// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eijdqiyvuhregbydndnb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVpamRxaXl2dWhyZWdieWRuZG5iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgwOTg3MTEsImV4cCI6MjA1MzY3NDcxMX0.3OwGu2t0-jvaGDihUbPptLdXdyy977PKQBDjnOmwelw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);